### ISSUE TITLE
Offer History Improvements

### ISSUE THREAD

**Issue by angelleye** [angelleye/offers-for-woocommerce#277]
* https://wordpress.org/support/topic/plugin-not-removing-messages-from-product-detail-page/#post-8729011

When an offer is made and the options are enabled to display offer history on the product page, but then the offer is declined, the product page still includes that offer as if it was current/pending.  Need to make sure this data only includes active/current offers.

**Comment by mdrahul** [comment]
We have resolved this issue already in the last merge which was Test_4.1. So now I think this should be resolved.

**Comment by angelleye** [comment]
@mdrahul Are you sure you aren't confusing this with the simple output of those divs that we just fixed yesterday?  This is a separate issue from that.

So in this case we need to make sure once an offer is declined it is no longer included in that history that gets displayed.  Is that what you're saying you already did here?

**Comment by mdrahul** [comment]
I am not confused. I have covered this in our Test_1.4 branch. I have removed the old logic from the plugin which was firing the manual query in the database and replaced it with wp_query provided by WP. You can test it from your side if you need to test.

**Comment by angelleye** [comment]
Okay, cool, I just wanted to confirm before I sat down to test this.  Thanks.

**Comment by angelleye** [comment]
We are still seeing the Highest Offer displayed even after declining the offer.

The offer count did remove itself, however, the highest offer is still displayed and shouldn't be.
